package mycalculator;

import javax.swing.ImageIcon;

public class Calculator extends javax.swing.JFrame {

    private double number1;
    private double number2;
    private String op;

    ImageIcon ic = new ImageIcon("calculator_icon.jpg");

    /**
     * Creates new form CalculatorUI
     */
    public Calculator() {

        // GUI
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setSize(400, 635);
        this.setTitle("myCalculator");
        this.setIconImage(ic.getImage());

        // Locked Components
        viewNumberInput.setEditable(false);
        ;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        viewNumberInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnID = new javax.swing.JButton();
        btnPercentage = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnSubtract = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(82, 109, 130));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(34, 37, 45));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(34, 37, 45));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 615));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Poppins ExtraLight", 2, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("created by @Daniel3131");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 40, 120, 20);

        viewNumberInput.setBackground(new java.awt.Color(40, 44, 54));
        viewNumberInput.setFont(new java.awt.Font("Poppins ExtraBold", 0, 22)); // NOI18N
        viewNumberInput.setForeground(new java.awt.Color(204, 204, 204));
        viewNumberInput.setBorder(null);
        viewNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewNumberInputActionPerformed(evt);
            }
        });
        jPanel1.add(viewNumberInput);
        viewNumberInput.setBounds(30, 60, 330, 50);

        jLabel2.setFont(new java.awt.Font("Poppins ExtraBold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("myCalculator");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 140, 40);

        jPanel2.setBackground(new java.awt.Color(45, 50, 61));

        btnAdd.setBackground(new java.awt.Color(39, 43, 52));
        btnAdd.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(118, 172, 222));
        btnAdd.setText("+");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnAC.setBackground(new java.awt.Color(39, 43, 52));
        btnAC.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnAC.setForeground(new java.awt.Color(158, 225, 168));
        btnAC.setText("AC");
        btnAC.setBorder(null);
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnID.setBackground(new java.awt.Color(39, 43, 52));
        btnID.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnID.setForeground(new java.awt.Color(158, 225, 168));
        btnID.setText("+/-");
        btnID.setBorder(null);
        btnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDActionPerformed(evt);
            }
        });

        btnPercentage.setBackground(new java.awt.Color(39, 43, 52));
        btnPercentage.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnPercentage.setForeground(new java.awt.Color(158, 225, 168));
        btnPercentage.setText("%");
        btnPercentage.setBorder(null);
        btnPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercentageActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(39, 43, 52));
        btn7.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(39, 43, 52));
        btn8.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(39, 43, 52));
        btn9.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnSubtract.setBackground(new java.awt.Color(39, 43, 52));
        btnSubtract.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnSubtract.setForeground(new java.awt.Color(118, 172, 222));
        btnSubtract.setText("-");
        btnSubtract.setBorder(null);
        btnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractActionPerformed(evt);
            }
        });

        btnMultiply.setBackground(new java.awt.Color(39, 43, 52));
        btnMultiply.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnMultiply.setForeground(new java.awt.Color(118, 172, 222));
        btnMultiply.setText("*");
        btnMultiply.setToolTipText("");
        btnMultiply.setBorder(null);
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(39, 43, 52));
        btn6.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(39, 43, 52));
        btn5.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(39, 43, 52));
        btn4.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnDivide.setBackground(new java.awt.Color(39, 43, 52));
        btnDivide.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnDivide.setForeground(new java.awt.Color(118, 172, 222));
        btnDivide.setText("/");
        btnDivide.setBorder(null);
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(39, 43, 52));
        btn1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(39, 43, 52));
        btn2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(39, 43, 52));
        btn3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(39, 43, 52));
        btnDelete.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(236, 99, 99));
        btnDelete.setText("DEL");
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(39, 43, 52));
        btn0.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.setBorder(null);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPoint.setBackground(new java.awt.Color(39, 43, 52));
        btnPoint.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnPoint.setForeground(new java.awt.Color(118, 172, 222));
        btnPoint.setText(".");
        btnPoint.setBorder(null);
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });

        btnEqual.setBackground(new java.awt.Color(39, 43, 52));
        btnEqual.setFont(new java.awt.Font("Poppins ExtraBold", 0, 18)); // NOI18N
        btnEqual.setForeground(new java.awt.Color(118, 172, 222));
        btnEqual.setText("=");
        btnEqual.setBorder(null);
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 140, 400, 490);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewNumberInputActionPerformed

    }//GEN-LAST:event_viewNumberInputActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Store the first number and the selected operator
        number1 = Double.parseDouble(viewNumberInput.getText());
        op = ((javax.swing.JButton) evt.getSource()).getText();

        // Clear the input field for the next number
        viewNumberInput.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        // Clear the viewNumberInput text field
        viewNumberInput.setText("");
    }//GEN-LAST:event_btnACActionPerformed

    private void btnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDActionPerformed
        // Get the current input from the viewNumberInput text field
        String input = viewNumberInput.getText();

        // Check if the input is not empty
        if (!input.isEmpty()) {
            // Check if the input already has a "+" or "-" sign
            if (input.charAt(0) == '-' || input.charAt(0) == '+') {
                // Remove the existing sign
                input = input.substring(1);
            } else {
                // Add a "-" sign in front of the input
                input = "-" + input;
            }

            // Update the viewNumberInput text field with the modified input
            viewNumberInput.setText(input);
        }
    }//GEN-LAST:event_btnIDActionPerformed

    private void btnPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercentageActionPerformed
        // Get the current input from the viewNumberInput text field
        String input = viewNumberInput.getText();

        // Convert the input to a numeric value
        double number = Double.parseDouble(input);

        // Calculate the percentage
        double percentage = number * 0.01;

        // Update the viewNumberInput text field with the percentage
        viewNumberInput.setText(Double.toString(percentage));
    }//GEN-LAST:event_btnPercentageActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractActionPerformed
        // Store the first number and the selected operator
        number1 = Double.parseDouble(viewNumberInput.getText());
        op = ((javax.swing.JButton) evt.getSource()).getText();

        // Clear the input field for the next number
        viewNumberInput.setText("");
    }//GEN-LAST:event_btnSubtractActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        // Store the first number and the selected operator
        number1 = Double.parseDouble(viewNumberInput.getText());
        op = ((javax.swing.JButton) evt.getSource()).getText();

        // Clear the input field for the next number
        viewNumberInput.setText("");
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        // Store the first number and the selected operator
        number1 = Double.parseDouble(viewNumberInput.getText());
        op = ((javax.swing.JButton) evt.getSource()).getText();

        // Clear the input field for the next number
        viewNumberInput.setText("");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Get the current text from the viewNumberInput text field
        String currentText = viewNumberInput.getText();

        // Check if there is any text to delete
        if (!currentText.isEmpty()) {
            // Remove the last character from the text
            String newText = currentText.substring(0, currentText.length() - 1);

            // Update the viewNumberInput text field with the new text
            viewNumberInput.setText(newText);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // Get the clicked button's label
        String buttonText = ((javax.swing.JButton) evt.getSource()).getText();

        // Append the button label to the input field
        viewNumberInput.setText(viewNumberInput.getText() + buttonText);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        // Get the current input from the viewNumberInput text field
        String input = viewNumberInput.getText();

        // Check if the input already contains a decimal point
        if (!input.contains(".")) {
            // Append a decimal point to the input
            String newInput = input + ".";
            viewNumberInput.setText(newInput);
        }
    }//GEN-LAST:event_btnPointActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // Store the second number
        number2 = Double.parseDouble(viewNumberInput.getText());

        // Perform the calculation based on the selected operator
        double result = 0;
        switch (op) {
            case "+":
                result = number1 + number2;
                break;
            case "-":
                result = number1 - number2;
                break;
            case "*":
                result = number1 * number2;
                break;
            case "/":
                result = number1 / number2;
                break;
        }

        // Display the result
        viewNumberInput.setText(String.valueOf(result));
    }//GEN-LAST:event_btnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPercentage;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnSubtract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField viewNumberInput;
    // End of variables declaration//GEN-END:variables
}
